Accessibility Tests for Newsletter
qxf2/newsletter_automation pull request #222
Opened 2023-11-17 17:21 UTC by ajitava-git

This PR is for accessibility tests for newsletter.

I have added a new method in the page factory to return all the pages. The pages are being iterated and injected axe-core and run for checking accessibility.

Once the accessibility checks are run, a snapshot is created for every page.

So, next time a new page is introduced, we just need to add it to the page factory, and the accessibility script will do the job.

An accessibility util is added which has the methods to inject, run, and write axe into the tests.

Steps to run the test:
1. Go to the accessibility _tests folder
2. Run the test using python -m pytest test_accessibility.py --snapshot-update (We use --snapshot-update only for the first time to create the snapshot directory)
3. Once the test is run, you can see the accessibility for each page inside the snapshot folder.

2023-11-21 07:03 UTC, shivahari requested changes

2023-11-21 07:03 UTC, shivahari commented on tests/integration/page_objects/PageFactory.py
> +            test_obj = Previewnewsletter_Page(base_url=base_url)
Can you add a comment here at the end saying any new page added needs to be updated in the `get_all_page_names` method too.

2023-11-21 14:05 UTC, ajitava-git commented on tests/integration/tests/accessibility_tests/test_accessibility.py
I think this was like how we have for ui_tests and api_tests (the directory structure?) under tests directory and another reason was that accessibility tests would have a snapshot folder for snapshot testing. Didn't quite understand "to help pytest find tests". This test is discoverable by pytest.

2023-11-21 14:06 UTC, ajitava-git commented on tests/integration/utils/axe.min.js
Yes @shivahari.. Make sense. Moved it.

2023-11-21 14:06 UTC, ajitava-git commented on tests/integration/page_objects/PageFactory.py
> +            test_obj = Previewnewsletter_Page(base_url=base_url)
Done.

2023-11-23 14:17 UTC, ajitava-git commented on tests/integration/page_objects/Base_Page.py
> +class Base_Page(Borg,unittest.TestCase, Accessibility_Util):
@shivahari Have implemented the suggested design pattern. Please review.

2023-11-24 08:12 UTC, shivahari approved these changes

2023-11-24 08:14 UTC, shivahari requested changes
Can you add `axe_selenium_python`  module to the `requirements.txt` file

2023-11-24 08:41 UTC, shivahari requested changes
Can you also add the command to run the test in the `deploy` GitHub workflow here https://github.com/qxf2/newsletter_automation/blob/main/.github/workflows/deploy.yaml#L47

2023-11-24 08:41 UTC, ajitava-git commented
> Can you add `axe_selenium_python` module to the `requirements.txt` file

Done @shivahari

2023-11-24 11:39 UTC, ajitava-git commented
> Can you also add the command to run the test in the `deploy` GitHub workflow here https://github.com/qxf2/newsletter_automation/blob/main/.github/workflows/deploy.yaml#L47

Done @shivahari and pushed.

2023-11-24 11:53 UTC, shivahari approved these changes

2023-11-24 13:12 UTC, rohandudam commented
@ajitava-git Can you please check CI run issue and make sure it will run fine as you touched the github action file with this PR.

2023-11-28 06:15 UTC, ajitava-git commented
> @ajitava-git Can you please check CI run issue and make sure it will run fine as you touched the github action file with this PR. Also think about the order of tests run, I feel it better to run the faster tests first before running slower tests like UI tests.

Done @rohandudam! For now, I have kept the order in this way. API Tests followed by Accessibility Tests followed by UI Tests.

2023-11-29 08:41 UTC, shivahari requested changes
The test seems to be missing from `tests/accessibility_tests` Ajitava.

2024-02-20 06:58 UTC, ajitava-git commented
> @ajitava-git Can you please check CI run issue and make sure it will run fine as you touched the github action file with this PR. Also think about the order of tests run, I feel it better to run the faster tests first before running slower tests like UI tests.

@rohandudam The accessibility tests run fine in CI now.

2024-02-21 10:11 UTC, rohandudam approved these changes

2024-02-21 10:13 UTC, ajitava-git commented on tests/integration/tests/accessibility_tests/snapshots/test_accessibility/test_accessibility/chrome/snapshot_output_add articles page.txt
Done

2024-02-21 10:13 UTC, ajitava-git commented on tests/integration/tests/accessibility_tests/snapshots/test_accessibility/test_accessibility/chrome/snapshot_output_add articles page.txt
Done

2024-02-26 08:10 UTC, shivahari approved these changes

2024-02-26 12:28 UTC, merged